AllCops:
  Exclude:
    - 'vendor/**/*'

Style/SpaceBeforeFirstArg:
  Exclude:
    - '**/Berksfile'
    - '**/metadata.rb'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Berksfile'

Metrics/LineLength:
  Max: 150

Style/RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Style/AlignParameters:
  Exclude:
    - '**/Gemfile'
